//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPISummaryPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HG_PDM
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        [Required(ErrorMessage = "A Product Code is required")]
        [DisplayName("ProductCode")]
        public string ProductCode { get; set; }
        [DisplayName("CountryOfOriginStatement")]
        public string CountryOfOriginStatement { get; set; }
        [DisplayName("IngredientsListDeclared")]
        public string IngredientListDeclared { get; set; }
        [DisplayName("ItemDescriptionWeb")]
        public string ItemDescriptionWeb { get; set; }
        [DisplayName("ProductDescriptionWeb")]
        public string ProductDescriptionWeb { get; set; }
        [DisplayName("WebCookingHintsAndTips")]
        public string WebCookingHintsAndTips { get; set; }
        [DisplayName("ItemWebsitePublicReleaseDate")]
        public string ItemWebsitePublicReleaseDate { get; set; }
        [DisplayName("ItemWebsiteFuturePublishDate")]
        public string ItemWebsiteFuturePublishDate { get; set; }
        [DisplayName("ItemWebsiteDeactivateDate")]
        public string ItemWebsiteDeactivateDate { get; set; }
        [DisplayName("ItemLaunchDate")]
        public string ItemLaunchDate { get; set; }
        [DisplayName("NutritionalInformationFooter")]
        public string NutritionalInformationFooter { get; set; }
        [DisplayName("GMO ")]
        public string GMO { get; set; }
        [DisplayName("IrradiatedIngredients")]
        public string IrradiatedIngredients { get; set; }
        [DisplayName("ServingSize")]
        public Nullable<double> ServingSize { get; set; }
        [DisplayName("ServingSizeUnitOfMeasure")]
        public string ServingSizeUnitOfMeasure { get; set; }
        [DisplayName("ServingsPerPackage")]
        public Nullable<double> ServingsPerPackage { get; set; }
        [DisplayName("Allergens")]
        public string Allergens { get; set; }
        [DisplayName("WebSegment")]
        public string WebSegment { get; set; }
        [DisplayName("WebSubSegment")]
        public string WebSubSegment { get; set; }
        [DisplayName("DependencyType")]
        public string DependencyType { get; set; }
        [DisplayName("Nutrients")]
        public string Nutrients { get; set; }
        [DisplayName("ConsumerStorageInstructions")]
        public string ConsumerStorageInstructions { get; set; }
        [DisplayName("Precautions")]
        public string Precautions { get; set; }
        [DisplayName("PreparationInstructions")]
        public string PreparationInstructions { get; set; }
        [DisplayName("PreparationState")]
        public string PreparationState { get; set; }
        [DisplayName("Claims")]
        public string Claims { get; set; }
        [DisplayName("Images")]
        public string Images { get; set; }
        [DisplayName("Introduction")]
        public string Introduction { get; set; }
        [DisplayName("LabelName")]
        public string LabelName { get; set; }
        [DisplayName("UpdateIndicator")]
        public string UpdateIndicator { get; set; }
        [DisplayName("RowNumber")]
        public Nullable<int> RowNumber { get; set; }
        [DisplayName("Transferred DateTime")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Datetime")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public Nullable<System.DateTime> TransferredDate { get; set; }
    }
}
