//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPISummaryPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [Serializable]
    public partial class iICE_Staging
    {
        public int ID { get; set; }
        [DisplayName("WebSegment")]
        public string WebSegment { get; set; }
        [DisplayName("WebSubSegment")]
        public string WebSubSegment { get; set; }
        [Required(ErrorMessage = "A Product Code is required")]
        [DisplayName("ProductCode")]
        public string ItemCode { get; set; }
        [DisplayName("ItemDescriptionWeb")]
        public string ItemDescriptionWeb { get; set; }
        [DisplayName("ItemNameWeb")]
        public string ItemNameWeb { get; set; }
        [DisplayName("BrandDescription")]
        public string BrandDescription { get; set; }
        [DisplayName("CookingHintsAndtips")]
        public string CookingHintsAndtips { get; set; }
        [DisplayName("CookingInstructions")]
        public string CookingInstructions { get; set; }
        [DisplayName("ProductDescriptionWeb")]
        public string ProductDescriptionWeb { get; set; }
        [DisplayName("ProductIngredients")]
        public string ProductIngredients { get; set; }
        [DisplayName("PackSize")]
        public string PackSize { get; set; }
        [DisplayName("ServingSize")]
        public string ServingSize { get; set; }
        [DisplayName("ServingsPerPackage")]
        public string ServingsPerPackage { get; set; }
        [DisplayName("Claims ")]
        public string Claims { get; set; }
        [DisplayName("Nutrition")]
        public string Nutrition { get; set; }
        [DisplayName("PublishDate")]
        public string PublishDate { get; set; }
        [DisplayName("UnPublishDate")]
        public string UnPublishDate { get; set; }
        [DisplayName("ChangeFlag ")]
        public string ChangeFlag { get; set; }
        [DisplayName("Images")]
        public string Images { get; set; }
        [DisplayName("Thumbnail")]
        public string Thumbnail { get; set; }
        [DisplayName("Introduction")]
        public string Introduction { get; set; }
        [DisplayName("FPI Run Date")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid Date")]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime TransferredDate { get; set; }
    }
}
