//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPISummaryPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xItemImagesHeader
    {
        public System.Guid xItemImageId { get; set; }
        public string xItemCode { get; set; }
        public string xItemDescriptionWeb { get; set; }
        public string xItemBrand { get; set; }
        public string xItemImageType { get; set; }
        public string xItemImageTypeId { get; set; }
        public string xItemImageSize { get; set; }
        public Nullable<int> xItemAssetType { get; set; }
    }
}
