//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPISummaryPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xItemClaim
    {
        public System.Guid xItemClaimId { get; set; }
        public string xItemClaim1 { get; set; }
        public string xItemBrand { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
