//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPISummaryPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xItemImagesDetail
    {
        public System.Guid xItemImageId { get; set; }
        public string ImageId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> ImageIsThumbnail { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
